@ECHO OFF
ECHO Borrando Base de Datos...
CALL "C:\\MariaDB\\bin\\mysql.exe" -u root --password=admin -e "DROP DATABASE IF EXISTS parqueadero;"
ECHO Creando Base de Datos...
CALL "C:\\MariaDB\\bin\\mysql.exe" -u root --password=admin -e "CREATE DATABASE parqueadero;"
ECHO Cargando Base de Datos ...
"C:\\MariaDB\\bin\\mysql.exe" -u root --password=admin parqueadero < db_backup_company.sql
ECHO Presione cualquier tecla para terminar...
PAUSE >nul